[app]
app_intro = """
This app allows you to visualize & search data in a geometric way
* Networks
* Maps 
* Origami of information
"""

[module_description]
networks = """
Check to launch forecast. \n
Networks makes it able to..
"""
